import { createApp } from "vue";
import { createPinia } from "pinia";
import Antd from "ant-design-vue";
import App from "./App.vue";
// import "ant-design-vue/dist/antd.css";
import "ant-design-vue/dist/antd.less";
// import "ant-design-vue/dist/antd.dark.less";
import router from "./router";
const app = createApp(App);
app.use(createPinia());
app.use(router).use(Antd).mount("#app");
